### POST createUser: OK
POST http://10.42.0.211:8080/api/users
content-type: application/json

{
    "UserName": "admin",
    "Password": "admin"
}

### POST login: OK
POST http://localhost:5000/api/auth/login
content-type: application/json

{
    "User_name": "admin",
    "Password": "admin123"
}


### POST login: Not OK
POST http://localhost:5000/api/auth/login
content-type: application/json

{
    "User_name": "admin",
    "Password": "admin"
}

### GET users: OK
GET http://5.38.136.63:8080/api/users
Authorization: application/json


### POST login: OK
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "admin123"
}
