### Regisztráció
POST http://5.38.136.63:8080/api/register
Content-Type: application/json

{
    "userName": "adminuser",
    "email": "adminuser@example.com",
    "password": "Test1234!",
    "rememberMe": true
}


### Bejelentkezés
POST http://5.38.136.63:8080/api/auth/login
Content-Type: application/json

{
    "userName": "adminuser",
    "password": "Test1234!",
    "rememberMe": true
}


### Token validálás
POST http://localhost:8080/api/auth/validate
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwidW5pcXVlX25hbWUiOiJkYW5pZWwiLCJ1c2VySWQiOiIyIiwiZXhwIjoxNzY1NDU3MTI5LCJpc3MiOiJjbGFzc2h1Yi1hcGkiLCJhdWQiOiJjbGFzc2h1Yi1jbGllbnQifQ.5miPI41UaZj_6mQqb9kSKDVvItwHLzwF9l6s2SoX6E8"
}


### Token frissítés
POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
    "refreshToken": "BhWnK4PyFznoEnfUL/pCAWIpnALXoyw7WUCMDKNFLYl6TAGQxYLSXU2Hx5Obwsf6AvcEFBm7xtTKKzaVnIDhsQ=="
}


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwidW5pcXVlX25hbWUiOiJhZG1pbnVzZXIiLCJ1c2VySWQiOiI1IiwiZXhwIjoxNzY1OTA5NDM2LCJpc3MiOiJjbGFzc2h1YiIsImF1ZCI6ImNsYXNzaHViIn0.jn60nN7ab2qm2Znp6LxAPeQl_2E8_td1-hcqLL1Yn8s
### Szervezet létrehozása
POST http://5.38.136.63:8080/api/org
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Tech Corp"
}



### Csoport létrehozása szervezeten belül
POST http://5.38.136.63:8080/api/org/3/groups
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Backend Team"
}


### Felhasználó meghívása szervezetbe
POST http://localhost:8080/api/org/3/invite
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "daniel@example.com",
    "roleId": 3
}


### Meghívó elfogadása
POST http://localhost:8080/api/invite/accept
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "token": "Sdm+80maQ6OxzRXlIVy6RD0Qf0ybM0KH6lkyCZKLsvvSbJZ2FTJyvBdO/LF9ThNe"
}