### Regisztráció
POST http://localhost:8080/api/register
Content-Type: application/json

{
    "userName": "daniel",
    "email": "daniel@example.com",
    "password": "Test1234!",
    "rememberMe": true
}


### Bejelentkezés
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "userName": "daniel",
    "password": "Test1234!",
    "rememberMe": true
}


### Token validálás
POST http://localhost:8080/api/auth/validate
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwidW5pcXVlX25hbWUiOiJkYW5pZWwiLCJ1c2VySWQiOiIyIiwiZXhwIjoxNzY1NDU0NzQ5LCJpc3MiOiJjbGFzc2h1Yi1hcGkiLCJhdWQiOiJjbGFzc2h1Yi1jbGllbnQifQ.XJYMsqLLbF2by2MR0QVr2HuiRQpMHkKiKOHXBUuwD8M"
}


### Token frissítés
POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
    "refreshToken": "8gVjAtfidEaJO0yYQW0keBKkYNQfnBp3u5JFO4gd/5/hbjGPaewTNdR7RyLWgU1zBiq3tW/7B3ZCjDBKE3Zz9A=="
}